apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: jupyterhub
  releaseName: test
  version: 1.2.0
  repo: https://jupyterhub.github.io/helm-chart
  valuesFile: values.yaml
  namespace: jupyterhub

patches:
  - path: ingress-patch.yaml