ingress:
  enabled: true
  # ingressClassName: traefik
  hosts:
  - jupyter-test.demo.akuity.io
rbac:
  enabled: false
prePuller:
  hook:
    enabled: false
  continuous:
    enabled: false
singleuser:
  image:
    name: jupyter/datascience-notebook
    tag: latest
proxy:
  secretToken: akuity